# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1637c9b9665a653820e37f76587f115bbd7d57e346667bd40f547139c52aab72fcfc5925258e5854def1cf2467ceda98c8b1a98075a525393a7d2b57cf7e061e

test:
  secret_key_base: 7fee14b02bf9994398e0e1680008d3ef06086a9ce44a44170cf92b9d9e30cf17c8a967407063a8d039c6fcaccdd4d9a5957aa60e961de48aadee653d099dea03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
